[package]
name = "stunne-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8", features = ["std", "std_rng"], default-features = false }
bytes = "1.1"
